# Generated by Django 3.2.16 on 2024-02-12 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50, verbose_name='Тикер')),
                ('name', models.CharField(max_length=255, verbose_name='Название бумаги')),
                ('type', models.CharField(max_length=50, verbose_name='Тип инструмента')),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
            },
        ),
        migrations.CreateModel(
            name='InstrumentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_posts.instrument', verbose_name='Бумага')),
            ],
            options={
                'verbose_name': 'Инструмент-пост',
                'verbose_name_plural': 'Инструмент-посты',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='Никнейм')),
                ('profile_tinkoff', models.CharField(max_length=255, verbose_name='Профиль Тинькофф')),
            ],
            options={
                'verbose_name': 'Инвестор',
                'verbose_name_plural': 'Инвесторы',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likesCount', models.PositiveIntegerField(verbose_name='Кол-во лайков')),
                ('commentsCount', models.PositiveIntegerField(verbose_name='Кол-во комментариев')),
                ('reactionsCount', models.PositiveIntegerField(verbose_name='Кол-во реакций')),
                ('inserted', models.DateField(verbose_name='Дата публикации')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_posts.investor', verbose_name='Инвестор')),
            ],
            options={
                'verbose_name': 'Пост по бумаге',
                'verbose_name_plural': 'Посты по бумаге',
            },
        ),
        migrations.DeleteModel(
            name='PostsTicker',
        ),
        migrations.AddField(
            model_name='instrumentpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse_posts.post', verbose_name='Пост'),
        ),
    ]
