# Generated by Django 4.0 on 2024-02-18 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_posts', '0002_auto_20240212_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instrument',
            field=models.ManyToManyField(related_name='total_posts', to='pulse_posts.Instrument'),
        ),
        migrations.AlterField(
            model_name='post',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_posts', to='pulse_posts.investor', verbose_name='Инвестор'),
        ),
        migrations.DeleteModel(
            name='InstrumentPost',
        ),
    ]
