# Generated by Django 4.0 on 2024-03-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_posts', '0003_post_instrument_alter_post_investor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='inserted',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
