# Generated by Django 3.2.16 on 2024-01-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameRus', models.CharField(max_length=20, verbose_name='Категория')),
                ('NameEng', models.CharField(max_length=20, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='Страна')),
                ('ShortName', models.CharField(max_length=2, verbose_name='Краткое название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='RequestParamsTopLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberLines', models.PositiveIntegerField(verbose_name='Количество новостей')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_news.categories', verbose_name='Категория')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_news.countries', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры топ новостей',
            },
        ),
    ]
