# Generated by Django 3.2.16 on 2024-01-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Наименование')),
                ('source', models.CharField(max_length=200, verbose_name='Источник')),
                ('author', models.CharField(max_length=200, verbose_name='Автор')),
                ('topic', models.CharField(max_length=50, verbose_name='Тема')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание')),
                ('url', models.CharField(max_length=2000, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.AlterField(
            model_name='requestparamstoplines',
            name='NumberLines',
            field=models.PositiveIntegerField(help_text='Макс кол-во: 100', verbose_name='Количество новостей'),
        ),
    ]
