# Generated by Django 3.2.16 on 2024-01-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_news', '0002_auto_20240108_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topnews',
            name='author',
            field=models.CharField(default='Неизветный автор', max_length=200, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='description',
            field=models.CharField(default='Нет описания', max_length=2000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='topnews',
            name='url',
            field=models.URLField(verbose_name='Ссылка'),
        ),
    ]
