# Generated by Django 3.2.16 on 2024-01-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_news', '0004_alter_topnews_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topnews',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Страны'),
        ),
    ]
