# Generated by Django 3.2.16 on 2024-01-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_news', '0008_topnewstranslated'),
    ]

    operations = [
        migrations.CreateModel(
            name='testImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Слава Лучший', max_length=20, verbose_name='Наименование')),
                ('test', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Тест Изображения',
                'verbose_name_plural': 'Тесты изображений',
            },
        ),
    ]
