# Generated by Django 3.2.16 on 2024-01-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_news', '0010_auto_20240115_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='Name',
            field=models.CharField(max_length=120, verbose_name='Страна'),
        ),
    ]
