# Generated by Django 4.0 on 2024-03-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_news', '0014_alter_topnews_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topnews',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Источник'),
        ),
    ]
