# Generated by Django 4.0 on 2024-04-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_news', '0016_alter_topnewsimages_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesGenerated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание картинки')),
                ('image', models.ImageField(upload_to='generated', verbose_name='Картинка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
