# Generated by Django 4.0 on 2024-04-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_news', '0017_imagesgenerated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_base', models.BooleanField(verbose_name='Базовая картинка')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Заставка',
                'verbose_name_plural': 'Заставки',
            },
        ),
        migrations.AddField(
            model_name='imagesgenerated',
            name='task_id',
            field=models.CharField(default='default-id', max_length=255, verbose_name='Идентификатор картинки'),
            preserve_default=False,
        ),
    ]
