# Generated by Django 4.0 on 2024-04-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_news', '0018_picturelinks_imagesgenerated_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesgenerated',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='generated', verbose_name='Картинка'),
        ),
    ]
