# Generated by Django 4.0 on 2024-04-15 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main_news', '0019_alter_imagesgenerated_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_news.imagesgenerated', verbose_name='Сгенерированные изображения')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='auth.user', verbose_name='Пользователь')),
            ],
        ),
    ]
