# Generated by Django 4.0 on 2024-07-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_news', '0020_userpictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesgenerated',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Картинка сгенерирована'),
        ),
    ]
